meta_product_name: "Kouakou'Ziner"
meta_title: "KouakouZiner - my app for new recipes if you are lazy"
meta_description: "An app that can find recipes with your ingredients in your fridge"
meta_image: "logo.png"

